"use client";

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarCheck2, Check, Clock3, Plus, Search, X } from "lucide-react";
import type { AppUser } from "@/types/auth";
import type { HrEmployee } from "../domain/hr-foundation";
import type { HrLeaveAction, HrLeaveDayPart, HrLeaveList, HrLeaveRequest, HrLeaveSource, HrLeaveStatus } from "../domain/hr-leave";
import { HttpHrRepository } from "../repositories/http-hr.repository";

const input = "h-11 w-full min-w-0 rounded-xl border border-white/[.08] bg-black/20 px-3 text-[11px] text-white outline-none focus:border-blue-400/40";
const statusText: Record<HrLeaveStatus, string> = { PENDING: "Onay Bekliyor", APPROVED: "Onaylandı", REJECTED: "Reddedildi", CANCELLED: "İptal Edildi" };
const sourceText: Record<HrLeaveSource, string> = { EMPLOYEE_REQUEST: "Çalışan Talebi", MANAGER_ENTRY: "Yönetici Kaydı", HR_MANUAL: "HR Manuel", SYSTEM: "Sistem" };

export function LeaveManagement({ user, employees }: { user: AppUser; employees: HrEmployee[] }) {
  const repository = useMemo(() => new HttpHrRepository(), []);
  const [data, setData] = useState<HrLeaveList | null>(null);
  const [selected, setSelected] = useState<HrLeaveRequest | null>(null);
  const [status, setStatus] = useState("ALL"); const [search, setSearch] = useState("");
  const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const refresh = useCallback(async () => {
    setLoading(true);
    try { setData(await repository.listLeaveRequests({ status: status as HrLeaveStatus | "ALL" })); setError(""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "İzinler yüklenemedi."); }
    finally { setLoading(false); }
  }, [repository, status]);
  useEffect(() => { void refresh(); }, [refresh]);
  const filtered = (data?.requests ?? []).filter(item => `${item.employeeName} ${item.employeeCode} ${item.leaveType}`.toLocaleLowerCase("tr").includes(search.toLocaleLowerCase("tr")));
  async function openDetail(id: string) { setLoading(true); try { setSelected(await repository.getLeaveRequest(id)); setCreating(false); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "İzin detayı yüklenemedi."); } finally { setLoading(false); } }
  async function transition(action: HrLeaveAction, reason: string) {
    if (!selected) return;
    setLoading(true);
    try { setSelected(await repository.transitionLeaveRequest(selected.id, action, reason, crypto.randomUUID())); await refresh(); }
    catch (value) { setError(value instanceof Error ? value.message : "İzin işlemi tamamlanamadı."); setLoading(false); }
  }
  const metrics = [["Onay Bekleyen", data?.metrics.pending ?? 0, Clock3], ["Bugün İzinde", data?.metrics.todayOnLeave ?? 0, CalendarCheck2], ["Bu Ay Onaylanan", data?.metrics.approvedThisMonth ?? 0, Check]] as const;
  return <div className="grid min-w-0 gap-4">
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{metrics.map(([label, value, Icon]) => <article key={label} className="mether-kpi p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] font-bold text-slate-500">{label}</div><div className="mt-3 text-2xl font-black text-white">{value}</div></div><div className="mether-kpi-icon h-9 w-9"><Icon size={15}/></div></div></article>)}</div>
    {error ? <div className="rounded-2xl border border-rose-500/20 bg-rose-500/10 p-4 text-[10px] text-rose-200">{error}</div> : null}
    <section className={`grid min-w-0 gap-4 ${(creating || selected) ? "xl:grid-cols-[minmax(0,1fr)_380px]" : ""}`}>
      <div className="mether-surface min-w-0 rounded-[24px] p-4 sm:p-5">
        <div className="flex flex-col gap-3 border-b border-white/[.06] pb-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-white">İzinler</h2><p className="mt-1 text-[9px] text-slate-500">Yetki kapsamınızdaki izin kayıtları · gün hesabı takvim günüdür.</p></div><button onClick={() => { setCreating(true); setSelected(null); }} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-[10px] font-black text-white"><Plus size={15}/> İzin Kaydı Ekle</button></div>
        <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_180px]"><label className="relative"><Search size={14} className="absolute left-3 top-3.5 text-slate-600"/><input value={search} onChange={event => setSearch(event.target.value)} className={`${input} pl-9`} placeholder="Çalışan veya izin türü ara"/></label><select value={status} onChange={event => setStatus(event.target.value)} className={input}><option value="ALL">Tüm durumlar</option>{Object.entries(statusText).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div>
        <div className="mt-4 space-y-2">{filtered.map(item => <button key={item.id} onClick={() => void openDetail(item.id)} className="grid w-full min-w-0 gap-3 rounded-2xl border border-white/[.06] bg-black/10 p-4 text-left transition hover:border-blue-400/25 sm:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)_100px_110px] sm:items-center"><div className="min-w-0"><div className="truncate text-[11px] font-black text-white">{item.employeeName}</div><div className="mt-1 text-[8px] text-blue-300">{item.employeeCode} · {item.leaveType}</div></div><div className="text-[9px] text-slate-400">{item.startsOn} → {item.endsOn}<div className="mt-1 text-[8px] text-slate-600">{item.calendarDays} gün</div></div><div className="text-[8px] font-bold text-slate-500">{sourceText[item.source]}</div><Status status={item.status}/></button>)}{!loading && !filtered.length ? <div className="mether-empty-state rounded-2xl p-8 text-center"><div className="text-[11px] font-black text-white">Bu filtrede izin kaydı yok.</div><p className="mt-2 text-[9px] text-slate-500">Yeni bir izin kaydı ekleyebilir veya filtreyi değiştirebilirsiniz.</p></div> : null}{loading ? <div className="p-8 text-center text-[9px] text-slate-600">İzin kayıtları yükleniyor…</div> : null}</div>
      </div>
      {creating ? <LeaveCreate user={user} employees={employees} repository={repository} onClose={() => setCreating(false)} onCreated={async request => { setCreating(false); setSelected(request); await refresh(); }}/> : null}
      {selected ? <LeaveDetail request={selected} onClose={() => setSelected(null)} onAction={transition}/> : null}
    </section>
    <p className="text-[8px] text-slate-700">Bugün metrikleri şirket timezone kaynağı bulunmadığı için UTC tabanlıdır.</p>
  </div>;
}

function LeaveCreate({ user, employees, repository, onClose, onCreated }: { user: AppUser; employees: HrEmployee[]; repository: HttpHrRepository; onClose: () => void; onCreated: (request: HrLeaveRequest) => Promise<void> }) {
  const isHr = ["CEO","PARTNER","HR","PLATFORM_ADMIN"].includes(user.role); const isManager = user.role === "MANAGER"; const selfCode = user.platformUserCode ?? "";
  const choices = employees.length ? employees : selfCode ? [{ employeeCode: selfCode, displayName: user.name } as HrEmployee] : [];
  const [employeeCode, setEmployeeCode] = useState(isHr || isManager ? choices[0]?.employeeCode ?? "" : selfCode); const [leaveType, setLeaveType] = useState("Yıllık İzin"); const [startsOn, setStartsOn] = useState(""); const [endsOn, setEndsOn] = useState(""); const [dayPart, setDayPart] = useState<HrLeaveDayPart>("FULL_DAY"); const [description, setDescription] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false);
  const source: HrLeaveSource = isHr ? "HR_MANUAL" : isManager ? "MANAGER_ENTRY" : "EMPLOYEE_REQUEST";
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { await onCreated(await repository.createLeaveRequest({ employeeCode, leaveType, startsOn, endsOn, dayPart, description, source: source as Exclude<HrLeaveSource,"SYSTEM">, interventionReason: reason, idempotencyKey: crypto.randomUUID() })); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="mether-surface min-w-0 rounded-[24px] p-5"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-blue-400">Yeni Kayıt</div><h3 className="mt-2 text-lg font-black text-white">İzin Kaydı Ekle</h3></div><button type="button" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] text-slate-500"><X size={15}/></button></div><div className="mt-5 grid gap-3"><label className="text-[8px] font-black uppercase tracking-[.12em] text-slate-500">Çalışan<select required value={employeeCode} disabled={!isHr && !isManager} onChange={event => setEmployeeCode(event.target.value)} className={`${input} mt-2`}>{choices.map(item => <option key={item.employeeCode} value={item.employeeCode}>{item.displayName} · {item.employeeCode}</option>)}</select></label><label className="text-[8px] font-black uppercase tracking-[.12em] text-slate-500">İzin Türü<input required value={leaveType} onChange={event => setLeaveType(event.target.value)} className={`${input} mt-2`}/></label><div className="grid grid-cols-2 gap-2"><label className="text-[8px] font-black uppercase tracking-[.12em] text-slate-500">Başlangıç<input required type="date" value={startsOn} onChange={event => setStartsOn(event.target.value)} className={`${input} mt-2`}/></label><label className="text-[8px] font-black uppercase tracking-[.12em] text-slate-500">Bitiş<input required type="date" value={endsOn} onChange={event => setEndsOn(event.target.value)} className={`${input} mt-2`}/></label></div><select value={dayPart} onChange={event => setDayPart(event.target.value as HrLeaveDayPart)} className={input}><option value="FULL_DAY">Tam gün</option><option value="HALF_DAY">Yarım gün</option></select><textarea value={description} onChange={event => setDescription(event.target.value)} className={`${input} h-24 py-3`} placeholder="Açıklama"/>{isHr ? <textarea required value={reason} onChange={event => setReason(event.target.value)} className={`${input} h-20 py-3`} placeholder="Müdahale gerekçesi (zorunlu)"/> : null}<button disabled={saving || !employeeCode} className="h-12 rounded-xl bg-blue-600 text-[10px] font-black text-white disabled:opacity-40">{saving ? "Kaydediliyor…" : "İzin Kaydını Oluştur"}</button></div></form>;
}

function LeaveDetail({ request, onClose, onAction }: { request: HrLeaveRequest; onClose: () => void; onAction: (action: HrLeaveAction, reason: string) => Promise<void> }) {
  const [reason, setReason] = useState("");
  return <aside className="mether-surface min-w-0 rounded-[24px] p-5"><div className="flex items-start justify-between"><div><div className="text-[9px] font-black uppercase tracking-[.16em] text-blue-400">İzin Detayı</div><h3 className="mt-2 text-lg font-black text-white">{request.employeeName}</h3><p className="mt-1 text-[9px] text-blue-300">{request.employeeCode}</p></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl border border-white/[.07] text-slate-500"><X size={15}/></button></div><div className="mt-5 rounded-2xl border border-white/[.06] bg-black/10 p-4"><Status status={request.status}/><div className="mt-4 text-[11px] font-black text-white">{request.leaveType}</div><div className="mt-2 text-[9px] text-slate-400">{request.startsOn} → {request.endsOn} · {request.calendarDays} gün</div><div className="mt-3 text-[8px] text-slate-600">{sourceText[request.source]}</div>{request.description ? <p className="mt-4 text-[9px] leading-5 text-slate-400">{request.description}</p> : null}</div><div className="mt-5"><div className="text-[8px] font-black uppercase tracking-[.14em] text-slate-500">İşlem Geçmişi</div><div className="mt-3 space-y-2">{request.history.map(item => <div key={item.id} className="rounded-xl border border-white/[.05] p-3"><div className="text-[9px] font-bold text-white">{item.eventType}</div><div className="mt-1 text-[8px] text-slate-600">{new Date(item.occurredAt).toLocaleString("tr-TR")}</div>{item.reason ? <div className="mt-2 text-[8px] text-slate-400">{item.reason}</div> : null}</div>)}</div></div>{request.allowedActions.some(action => action !== "APPROVE") ? <textarea value={reason} onChange={event => setReason(event.target.value)} className={`${input} mt-5 h-20 py-3`} placeholder="Red veya iptal gerekçesi"/> : null}{request.allowedActions.length ? <div className="mt-3 grid gap-2">{request.allowedActions.map(action => <button key={action} disabled={action !== "APPROVE" && !reason.trim()} onClick={() => void onAction(action, action === "APPROVE" ? "" : reason)} className={`h-11 rounded-xl text-[9px] font-black disabled:opacity-35 ${action === "APPROVE" ? "bg-blue-600 text-white" : "border border-white/[.08] text-slate-300"}`}>{action === "APPROVE" ? "Onayla" : action === "REJECT" ? "Reddet" : "İptal Et"}</button>)}</div> : null}</aside>;
}
function Status({ status }: { status: HrLeaveStatus }) { const color = status === "APPROVED" ? "text-emerald-300 bg-emerald-400/[.08]" : status === "PENDING" ? "text-amber-300 bg-amber-400/[.08]" : status === "REJECTED" ? "text-rose-300 bg-rose-400/[.08]" : "text-slate-400 bg-white/[.04]"; return <span className={`w-fit rounded-full px-2.5 py-1.5 text-[7px] font-black uppercase tracking-[.12em] ${color}`}>{statusText[status]}</span>; }
